ForbesLindesay/atdatabases

packages/mysql-test/package.json, packages/pg-test/package.json, packages/with-container/package.json, packages/with-container/src/index.ts
This seems to cause problems when trying to use docker on Circle CI. It seems best to just be tolerant of some lines not being valid JSON.
=> fix: don't fail if JSON.parse fails on docker output for pg-test/mysql-test

package.json, packages/mysql-config/package.json, packages/mysql-test/README.md, packages/mysql-test/package.json, packages/mysql/package.json, packages/pg-config/package.json, packages/pg-test/README.md, packages/pg-test/package.json, packages/pg/package.json, packages/sqlite/README.md, packages/sqlite/package.json
This was producing a deprecation warning on install.
=> fix: remove stub types for ajv

docs/mysql.md, docs/pg.md, docs/sqlite.md, package.json, packages/mysql/package.json, packages/mysql/src/__tests__/stream.test.ts, packages/mysql/src/index.ts, packages/mysql/src/raw.ts, packages/pg-create/package.json, packages/pg-migrations/package.json, packages/pg-schema/package.json, packages/pg/package.json, packages/pg/src/__tests__/stream.test.ts, packages/pg/src/index.ts, packages/push-to-async-iterable/package.json, packages/push-to-async-iterable/src/__tests__/index.test.ts, packages/push-to-async-iterable/src/index.ts, packages/sqlite/package.json, packages/sqlite/src/__tests__/stream.test.ts, packages/sqlite/src/index.ts, yarn.lock
This adds a proper documented method for querying a database and streaming the results out. This can be used for querying very large tables when you want to fetch all results and process them as a stream.
[closes #38]
=> feat: `queryStream` returns an AsyncIterableIterator

docs/sql.md, packages/mysql/package.json, packages/pg/package.json, packages/sql/package.json, packages/sql/src/SQLQuery.ts, packages/sql/src/__tests__/fixture.sql, packages/sql/src/__tests__/index.test.ts, packages/sql/src/index.ts, packages/sqlite/package.json, packages/websql-core/package.json
This reads a file containing an SQL query in utf8 text, and returns it as an SQLQuery. It's generally most useful for large blocks of SQL, like database migrations.
```ts
const migration = sql.file(`${__dirname}/my-migration.sql`);
db.query(migration);
```
> N.B. if you allow users to write to the files that you later read in as queries via this method, your code will be vulnerable to SQL Injeciton. Only read in trusted files created by your own team of developers.
[closes #35]
=> feat: add "sql.file" method for reading in SQL from files

docs/mysql.md, docs/pg.md, docs/sqlite.md, packages/mysql/src/index.ts, packages/sqlite/src/index.ts
BREAKING CHANGE: we now export interfaces rather than classes. This makes more sense as we don't want people to construct/interact with the classes directly.
=> feat: support CommonJS in MySQL and SQLite

packages/sql/src/SQLQuery.ts
BREAKING CHANGE: if you were using values with quotes around them to construct an SQL query, that will now error. This shouldn't cause any issues as the resulting query would not have been valid anyway.
=> feat: error on quoted values (BREAKING CHANGE)

docs/sql.md, packages/mysql/src/__tests__/stream.test.ts, packages/pg-schema/src/getAttributes.ts, packages/pg-schema/src/getClasses.ts, packages/pg-schema/src/getConstraints.ts, packages/pg-schema/src/getEnumValues.ts, packages/pg-schema/src/getTypes.ts, packages/pg/src/__tests__/stream.test.ts, packages/sql/src/SQLQuery.ts, packages/sql/src/__tests__/index.test.ts, packages/sql/src/index.ts, packages/sqlite/src/__tests__/stream.test.ts
[closes #36]
For now, we don't actually break code that uses string literal delimiters, but we do log a warning to the console, so I'm going to treat this as a breaking change anyway.
=> feat: deprecate passing strings to sql.join

packages/expo/package.json, packages/mysql/package.json, packages/pg-create/package.json, packages/pg-migrations/package.json, packages/pg-schema/package.json, packages/pg/package.json, packages/sql/package.json, packages/sqlite/package.json, packages/websql-core/package.json, packages/websql/package.json
expo 2.0.1 -> 3.0.0
mysql 1.1.0 -> 2.0.0
pg 1.2.0 -> 2.0.0
sql 1.1.0 -> 2.0.0
sqlite 1.1.0 -> 2.0.0
websql-core 2.0.1 -> 3.0.0
websql 2.0.1 -> 3.0.0
=> chore: release packages

.circleci/config.yml
It isn't needed and it prevents the build from running.
=> fix: do not pass common-env context to non-master builds

.circleci/config.yml, expo-test-project/package.json, package.json, packages/expo/package.json, packages/mysql-config/package.json, packages/mysql-test/package.json, packages/mysql/package.json, packages/pg-config/package.json, packages/pg-create/package.json, packages/pg-data-type-id/package.json, packages/pg-errors/package.json, packages/pg-migrations/package.json, packages/pg-schema/package.json, packages/pg-schema/src/getSearchPath.ts, packages/pg-test/package.json, packages/pg/package.json, packages/push-to-async-iterable/package.json, packages/sql/package.json, packages/sqlite/package.json, packages/websql-core/package.json, packages/websql/package.json, packages/with-container/package.json, packages/with-container/src/run.ts, scripts/build-all.js, scripts/build.js, yarn.lock
TODO: I should probably mark all the version number of the individual packages as `0.0.0` to avoid them being mistaken for real version numbers. I should probably also take this opportunity to upgrade all the dependencies.
=> ci: use rollingversions to publish and remove bolt

packages/pg-typed/src/index.ts
It should be possible to re-export the `Table` type, but currently TypeScript complains that it cannot be named.
=> fix: pg typed re-exporting Table

packages/pg-typed/src/__tests__/index.test.ts, packages/pg-typed/src/index.ts, packages/sql/src/SQLQuery.ts
The syntax was wrong for `update` and `insertOrUpdate`. Both of these now have tests.
=> fix: support update in pg-typed

packages/pg-connection-string/package.json, packages/pg-connection-string/src/Configuration.ts, packages/pg-connection-string/src/EnvironmentVariables.ts, packages/pg-connection-string/src/__tests__/index.test.ts, packages/pg-connection-string/src/__tests__/snapshots.json, packages/pg-connection-string/src/index.ts, packages/pg-connection-string/src/parseConnectionURI.ts, packages/pg-connection-string/src/parseKeywordValueConnectionString.ts
This will enable us to properly support all `sslmode` values in the future, as well as enabling us to parse the key/value form of connection strings.
=> feat: create a library for parsing postgres connection strings

packages/pg-typed/src/__tests__/index.test.pg.ts, packages/pg-typed/src/index.ts
The `.select(whereCondition)` syntax was confusing to people who were new to the library because you're filtering the rows, not selecting the columns.
=> refactor: rename `.select` to `.find`

packages/pg-typed/src/__tests__/advancedQueries.test.pg.ts, packages/pg-typed/src/index.ts
The results are still limited to a single table, but it is now possible to use `anyOf`, `not`, `greaterThan` and `lessThan` to construct significantly more complex queries. For maximum flexibility, the `inQueryResults` condition lets you check if a value is in the results of another (untyped) SELECT query.
=> feat: add a method for more advanced queries in pg-typed

packages/pg/src/index.ts
This is a closer match for the default behaviour of most postgres clients. You can still perform ssl verification by providing `sslcert`, `sslkey`, `sslrootcert` or by specifying the ssl options when constructing the client.
=> fix: do not verify ssl certificates when no certs were provided

docs/sql.md
This was caused by copying and pasting from some of the libraries that inspired `@databases` We didn't implement this specific API though, so this example was failing.
[fixes #122]
=> docs: use `sql` not `sql.query`

packages/pg/package.json, packages/pg/src/__tests__/index.test.pg.ts, packages/pg/src/operations/queries.ts, packages/pg/src/operations/savepoint.ts, packages/pg/src/operations/transaction.ts, yarn.lock
They get broken within the underlying pg client because it's not all simple async/await, so we catch and re-throw these errors. They also got broken in throat, which I've been able to resolve.
=> feat: preserve async stack traces in pg

README.md, docs/connection-pool.md, packages/connection-pool/README.md, packages/connection-pool/package.json, packages/connection-pool/src/Queue.ts, packages/connection-pool/src/__tests__/Queue.test.ts, packages/connection-pool/src/__tests__/index.test.ts, packages/connection-pool/src/index.ts, website/i18n/en.json, website/sidebars.json
Not depending on the connection pool implementations from the pg driver and mysql drivers will give us much greater flexibility, and ultimately allow better code sharing between MySQL, Postgres & others
=> feat: add generic connection-pool implementation

docs/mysql-queryable.md, docs/mysql-transaction.md, docs/pg-queryable.md, docs/pg-transaction.md, packages/mock-db/src/ConnectionPool.ts, packages/mysql/src/ConnectionPool.ts, packages/mysql/src/types/Queryable.ts, packages/pg/src/ConnectionPool.ts, packages/pg/src/types/Queryable.ts, packages/shared/src/BaseConnection.ts, packages/shared/src/BaseConnectionPool.ts, packages/shared/src/BaseTransaction.ts, packages/shared/src/Factory.ts, packages/shared/src/index.ts, packages/shared/src/utils.ts
This lets you add a "post commit" step. This can be used for clearing caches after updating values.
=> feat: add a utility for queueing an action after commit

packages/mysql-test/src/commands.ts, packages/pg-test/src/commands.ts
In particular, this changes the help output to give the proper flags for changing the PG user and database (`--user` and `--database` rather than `-user` and `-database`, respectively). Also fixes some other minor inconsistencies in the help command output.
=> fix(pg-test): use proper command line flag in help command output

packages/mock-db-typed/package.json, packages/mock-db-typed/src/index.ts, packages/pg-typed/package.json, packages/pg-typed/src/index.ts
It causes completely useless errors to be thrown in production. It may make sense for client side JavaScript, but for node.js you want the actual error message to be shown.
=> fix: remove tiny-invariant

packages/connection-pool/src/PoolOptions.ts, packages/connection-pool/src/index.ts, packages/connection-pool/src/utils/errors.ts, packages/pg/src/ConnectionPool.ts, packages/pg/src/__tests__/too-many-connections-for-role.test.pg.ts
This automatically handles the error:
> too many connections for role "role_name"
from Postgres, providing we were able to create at least 1 connection for the pool. It will attempt to create connections again 5 seconds after encountering this error.
=> feat: automatically handle "too many connections for role" error in pg

packages/pg-typed/src/index.ts, tslint.json
This makes it harder to accidentally try to insert non-existant fields in pg-typed queries.
=> fix: stricter types for pg-typed's insert

docs/blog/2022-01-21-optimizing-postgres-using-unnest.md, docs/pg-bulk.md, packages/pg-bulk/src/__tests__/index.test.pg.ts, packages/pg-bulk/src/__tests__/unnest-blog.test.pg.ts, packages/pg-bulk/src/index.ts
You can use one `UNNEST` call with multiple arrays. This is the recommended way to produce records like this.
Thanks to [truilus on Reddit](https://www.reddit.com/r/PostgreSQL/comments/s9cw32/comment/htm2849/?utm_source=reddit&utm_medium=web2x&context=3) for the suggestion.
=> refactor: cleaner unnest usage

docs/pg-guide-connections.md, docs/pg-options.md, docs/pg-provider-google-cloud.md, docs/pg-provider-heroku.md, docs/sidebars.json, packages/pg/src/index.ts, packages/website/components/CodeBlock.tsx, packages/website/components/Document.tsx, packages/website/pages/_app.tsx, packages/website/utils/syntaxHighlight.ts, yarn.lock
This lets you use `$PGHOST`, `$PGUSER` etc. to configure your connection, which can work better in environments that expect you to connect using a unix socket and/or if you want to store only your database password in a secret manager.
=> feat: allow using @databases/pg without a connection string

docs/mysql-test.md, docs/pg-test.md
Trying the other paths didn't work, these paths are what is indeed installed.
=> docs(mysql-test): set correct import paths for setup and teardown

packages/mysql-schema-cli/src/index.ts, packages/pg-schema-cli/src/index.ts
Found through personal use that there wasn't a built-in way to specify the schema to the `pg-schema-cli` package, but that the `getSchema` function it uses has that functionality, so I thought I'd put together the lego blocks, so to speak.
Later noticed the same deal was true of `mssql-schema-cli`, so took the liberty of doing that, too.
=> Add schema param to mssql/pg-schema-cli

packages/with-container/src/index.ts
To support m1 devices for example https://github.com/ForbesLindesay/atdatabases/issues/214
=> Always run container in amd64 platform

packages/mysql-schema-print-types/src/__tests__/print-from-code.test.ts, packages/pg-schema-print-types/src/__tests__/print-from-code.test.ts, packages/shared-print-types/src/PrintContext.ts
This produces more stable output when generating types
=> feat: sort generated type declarations

docs/pg-typed.md
Ensure `allOf` section has a header referencing the correct field query (was previously referencing `anyOf`) and ensure it imports `allOf` from `@databases/pg-typed`
=> [DOCS]: Fix `allOf` field query section

packages/sqlite/src/__tests__/index.test.ts, packages/sqlite/src/index.ts
Here there should be an `await` https://github.com/ForbesLindesay/atdatabases/blob/master/packages/sqlite/src/index.ts#L128
Without it, `result` is a unresolved `Promise`, so the `COMMIT` is always executed. 
Added a small test to be sure that the rollback is done if `fn` throws.
=> Missing await on transaction in sqlite breaks rollback

docs/mysql-guide-typescript.md
Looks like by default, following the docs, @databases/mysql-schema-cli accesses all databases a user has and generates too much files/types, not taking into account specified schema name. Looks like there is a dedicated, not documented `schemaName` param now used for that..
update docs to use `--schemaName` param
=> fix documentation of @databases/mysql-schema-cli with --schemaName param

packages/sqlite-sync/package.json, yarn.lock
This enables `@databases/sqlite-sync` to run on Node v20.
=> Bumped better-sqlite3 to v8

packages/pg-migrations/src/PostgresDatabaseEngine.ts, packages/pg-schema-introspect/src/__tests__/getTypes.test.pg.ts
Fixes #278
During development I've encountered a flaky test for `pg-migrations` module - it looks like running tests in parallel can cause some of migration tests to fail. In particular on my local environment I can reproduce failures of dry-run test after applying migrations when running full test suite:
```shell 
yarn test --verbose
```
Failing test:
I think I narrowed down the root cause to [getSearchPath](https://github.com/ForbesLindesay/atdatabases/blob/8af7cdc8711a86998523e9a62594b612ba9e0f4b/packages/pg-schema-introspect/src/__tests__/getSearchPath.test.pg.ts#L19) test - it creates new schema which is going to be included into default PG search path (since it matches PG user name), so if schema is created between two migration tests it might appear as migration hasn't been applied …
=> Use server_version setting to resolve current PG version.

packages/sqlite-sync/package.json, yarn.lock
`better-sqlite3` major upgrade.
The major is because they dropped the support of node 16 (which is EOL). See: https://github.com/WiseLibs/better-sqlite3/releases/tag/v9.0.0
=> better-sqlite upgrade

packages/pg-config/src/PgConfig.ts, packages/pg-schema-print-types/src/printers/printClassDetails.ts
This should make it more useful by allowing you to still use it when using autogenerated ID columns.
=> feat: limit explicit defaults to static values
